name = "hono-medium-app"
main = "src/index.ts"
compatibility_date = "2024-10-10"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "<ADD YOUR POOLING URL FOR YOUR WORKER>"
JWT_SECRET = "<ADD A SECRET FOR YOUR JWT>"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1